# Generated by Django 3.1.7 on 2021-03-25 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articleapp', '0004_article_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dislike_users',
            field=models.ManyToManyField(related_name='dislike_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
