# Generated by Django 3.1.5 on 2021-04-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0005_article_dislike_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='create_at',
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
